language: node_js
node_js:
  - "8.11.1"
addons:
    code_climate:
        repo_token: 919203d715d0f3db85103b7be83f4b8d95e8ffd36db01707302bfc2ca67273a5 
before_script:
after_script:
  - codeclimate-test-reporter < lcov.info