service: fws
provider:
  name: aws
  stackName: ${env:FWS_ENV_NAME}${self:service}
  apiName: ${env:FWS_ENV_NAME}${self:service}-rest-api
  runtime: nodejs12.x
  role: ${env:FWS_LAMBDA_ROLE}
  stage: ${env:FWS_ENV_NAME}
  region: ${env:FWS_REGION}
  deploymentBucket:
    name: ${env:FWS_BUCKET}
  environment:
    stage: ${env:FWS_ENV_NAME}
    FWS_DB_CONNECTION: ${env:FWS_DB_CONNECTION}
    FWS_SNS_TOPIC: ${env:FWS_SNS_TOPIC}
    FWS_HTTP_PROXY: ${env:FWS_HTTP_PROXY}
    FWS_FE_TAG: ${env:FWS_FE_TAG}
  vpc:
    securityGroupIds:
      - ${env:FWS_VPN_SEC_GRP}
    subnetIds:
      - ${env:FWS_SUB_1}
      - ${env:FWS_SUB_2}
  apiGateway:
    restApiId: ${env:FWS_API_ID}
    restApiRootResourceId: ${env:FWS_ROOT_ID}
  logs:
    restApi:
      accessLogging: false
      executionLogging: true
      level: INFO
      fullExecutionData: true
package:
  exclude:
    - test
functions:
  processMessage:
    name: ${env:FWS_ENV_NAME}${self:service}-processMessage
    handler: lib/functions/process-message.handler
    events:
      - http:
          method: post
          path: message
          integration: lambda
          request:
            passThrough: WHEN_NO_TEMPLATES
            template:
              text/html: '{ "bodyXml": $input.json("$")}'
              application/json: ''
              application/x-www-form-urlencoded: ''
          authorizer: 
            name: authorizer
            type: request
            identitySource: method.request.header.x-api-key
            resultTtlInSeconds: 0
          response:
            headers:
              X-DNS-Prefetch-Control: "'off'"
              Strict-Transport-Security: "'max-age=15552000; includeSubDomains; preload'"
              X-Download-Options: "'noopen'"
              X-Content-Type-Options: "'nosniff'"
              Referrer-Policy: "'no-referrer'"
  # activateTargetArea:
  #   name: ${env:FWS_ENV_NAME}${self:service}-activateTargetArea
  #   handler: lib/functions/activate-target-area.handler
  #   events:
  #     - http:
  #         method: post
  #         path: activate-target-area
  #         integration: lambda
  #         request:
  #           passThrough: WHEN_NO_TEMPLATES
  #           template:
  #             text/html: '{ "bodyXml": $input.json("$")}'
  #             application/json: ''
  #             application/x-www-form-urlencoded: ''
  #         authorizer: 
  #           name: authorizer
  #           type: request
  #           identitySource: method.request.header.x-api-key
  #           resultTtlInSeconds: 0
  # deactivateTargetArea:
  #   name: ${env:FWS_ENV_NAME}${self:service}-deactivateTargetArea
  #   handler: lib/functions/deactivate-target-area.handler
  #   events:
  #     - http: 
  #         method: post
  #         path: deactivate-target-area
  #         integration: lambda
  #         request:
  #           passThrough: WHEN_NO_TEMPLATES
  #           template:
  #             text/html: '{ "bodyXml": $input.json("$")}'
  #             application/json: ''
  #             application/x-www-form-urlencoded: ''
  #         authorizer: 
  #           name: authorizer
  #           type: request
  #           identitySource: method.request.header.x-api-key
  #           resultTtlInSeconds: 0
  getAllMessages:
    name: ${env:FWS_ENV_NAME}${self:service}-getAllMessages
    handler: lib/functions/get-all-messages.handler
    events:
      - http:
          method: get
          path: fwis.xml
          authorizer: 
            name: authorizer
            type: request
            identitySource: method.request.header.x-api-key
            resultTtlInSeconds: 0
      - http:
          method: get
          path: fwis.json
          authorizer: 
            name: authorizer
            type: request
            identitySource: method.request.header.x-api-key
            resultTtlInSeconds: 0
      - http:
          method: get
          path: fwis-plus.json
          authorizer:
            name: authorizer
            type: request
            identitySource: method.request.header.x-api-key
            resultTtlInSeconds: 0
  getAllTargetAreas:
    name: ${env:FWS_ENV_NAME}${self:service}-getAllTargetAreas
    handler: lib/functions/get-all-target-areas.handler
    events:
      - http:
          method: get
          path: target-areas.json
          authorizer: 
            name: authorizer
            type: request
            identitySource: method.request.header.x-api-key
            resultTtlInSeconds: 0
  getAllHistoricalMessages:
    name: ${env:FWS_ENV_NAME}${self:service}-getAllHistoricalMessages
    handler: lib/functions/get-all-historical-messages.handler
    events:
      - http:
          method: get
          path: historical-messages/{code}
          authorizer: 
            name: authorizer
            type: request
            identitySource: method.request.header.x-api-key
            resultTtlInSeconds: 0
  authorizer:
    name: ${env:FWS_ENV_NAME}${self:service}-authorizer
    handler: lib/functions/authorizer.handler
plugins:
  - serverless-layers
# Uncomment folling lines when running serverless offline instance
#
# plugins:
# - serverless-offline
# custom:
#   serverless-offline:
#     port: 8050
