services:
  fwspgadmin:
    image: dpage/pgadmin4
    user: pgadmin
    env_file:
      - .env
    volumes:
      # IMPORTANT
      # Named volumes ensure portability across the host plaforms used to
      # create and run development containers.
      - fwspgadmin:/var/lib/pgadmin
    ports:
      - "127.0.0.1:8080:80"
    networks:
      ls:
  liquibase:
    image: liquibase/liquibase
    depends_on:
      fwsdb:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      # IMPORTANT
      # Named volumes ensure portability across the host plaforms used to
      # create and run development containers.
      - fwsliquibase:/fwsdb
    networks:
      ls:
    command: update
volumes:
  fwspgadmin:
    external: true
  fwsliquibase:
    external: true